BaseURL = "https://yokaze.github.io/"
copyright = "&copy; Rue Yokaze"
disableKinds = ["sitemap"]
googleAnalytics = "UA-83271338-1"
hascjklanguage = true
languageCode = "ja"
pluralizeListTitles = false
publishDir = "yokaze.github.io"
title = "yokaze.github.io"

[[menu.main]]
  name = "About"
  url = "/about/"

[[menu.main]]
  name = "Software"
  url = "/software/"
