BaseURL = "https://yokaze.github.io/"
copyright = "&copy; Rue Yokaze"
disableKinds = ["sitemap"]
googleAnalytics = "UA-83271338-1"
hascjklanguage = true
languageCode = "ja"
pluralizeListTitles = false
publishDir = "yokaze.github.io"
title = "yokaze.github.io"

[[menu.main]]
  name = "About"
  url = "/about/"

[[menu.main]]
  name = "Software"
  url = "/software/"

[taxonomies]
  category = "categories"

[related]
  includeNewer = true
  threshold = 10
  toLower = false

[[related.indices]]
  name = "keywords"
  weight = 150

[[related.indices]]
  name  = "categories"
  weight = 100

[[related.indices]]
  name  = "tags"
  weight = 100

[[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2006"
